// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMusic.Data;

#nullable disable

namespace RazorPagesMusic.Migrations
{
    [DbContext(typeof(MusicContext))]
    partial class MusicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("RazorPagesMusic.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Aurora Ray",
                            Genre = "Indie Pop",
                            Rating = "Good",
                            ReleaseDate = new DateTime(2018, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight Sun"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "The Nomads",
                            Genre = "Folk-Rock",
                            Rating = "Better",
                            ReleaseDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Desert Roads"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Vivid Echo",
                            Genre = "Synthwave",
                            Rating = "Best",
                            ReleaseDate = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neon Skyline"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Harbour Lights",
                            Genre = "Jazz",
                            Rating = "Good",
                            ReleaseDate = new DateTime(2015, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blue Harbor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
